// Mock Data for Middle East International Logistics Insurance Platform

const DATA = {
  // KPI Data
  kpi: {
    marketSize: 8.7,      // billion USD
    growthRate: 12.4,     // percent
    claimRatio: 34.2,     // percent
    coverageRate: 61.8,   // percent
  },

  // Premium trend 2020-2025
  premiumTrend: {
    labels: ['2020', '2021', '2022', '2023', '2024', '2025'],
    datasets: [{
      label: '保费规模（亿美元）',
      data: [42.3, 48.1, 55.7, 63.2, 74.8, 87.1],
      borderColor: '#d4a017',
      backgroundColor: 'rgba(212, 160, 23, 0.15)',
      borderWidth: 2.5,
      pointBackgroundColor: '#d4a017',
      pointRadius: 5,
      tension: 0.4,
      fill: true,
    }]
  },

  // Insurance penetration by country
  penetrationByCountry: {
    labels: ['沙特阿拉伯', '阿联酋', '伊朗', '以色列', '也门', '土耳其', '埃及'],
    datasets: [{
      label: '保险渗透率（%）',
      data: [72.4, 85.1, 38.6, 78.3, 12.7, 65.9, 44.2],
      backgroundColor: [
        'rgba(26, 54, 93, 0.85)',
        'rgba(212, 160, 23, 0.85)',
        'rgba(189, 72, 72, 0.85)',
        'rgba(72, 149, 189, 0.85)',
        'rgba(189, 72, 72, 0.65)',
        'rgba(95, 158, 95, 0.85)',
        'rgba(150, 120, 60, 0.85)',
      ],
      borderColor: [
        '#1a365d', '#d4a017', '#bd4848', '#4895bd', '#bd4848', '#5f9e5f', '#96783c'
      ],
      borderWidth: 1.5,
      borderRadius: 4,
    }]
  },

  // Insurance type distribution
  insuranceTypes: {
    labels: ['海运险', '空运险', '陆运险', '多式联运险'],
    datasets: [{
      data: [48.5, 22.3, 18.7, 10.5],
      backgroundColor: [
        'rgba(26, 54, 93, 0.88)',
        'rgba(212, 160, 23, 0.88)',
        'rgba(72, 149, 189, 0.88)',
        'rgba(95, 158, 95, 0.88)',
      ],
      borderColor: ['#1a365d', '#d4a017', '#4895bd', '#5f9e5f'],
      borderWidth: 2,
      hoverOffset: 8,
    }]
  },

  // Risk alerts (scrolling)
  riskAlerts: [
    { level: 'high',   icon: '⚠️', text: '红海航线：胡塞武装袭击频率上升，建议绕行好望角' },
    { level: 'medium', icon: '⚡', text: '霍尔木兹海峡：伊朗-美国紧张局势，通行延误预计+2天' },
    { level: 'low',    icon: 'ℹ️', text: '苏伊士运河：通行恢复正常，拥堵指数下降至低水平' },
    { level: 'high',   icon: '⚠️', text: '也门海域：无人机威胁持续，船舶保险附加费率上调15%' },
    { level: 'medium', icon: '⚡', text: '波斯湾：沙尘暴天气预警，空运延误风险中等' },
    { level: 'low',    icon: 'ℹ️', text: '土耳其博斯普鲁斯海峡：通行正常，保险费率稳定' },
    { level: 'medium', icon: '⚡', text: '阿拉伯海：季风季节临近，海上货损风险升高' },
    { level: 'high',   icon: '⚠️', text: '伊朗制裁更新：部分货物类别保险覆盖受限' },
  ],

  // Logistics tracking data
  logistics: {
    'ME20250001': {
      trackingNo: 'ME20250001',
      carrier: '地中海航运（MSC）',
      vessel: 'MSC DUBAI EXPRESS',
      voyage: 'ME2501W',
      origin: '上海港',
      destination: '迪拜杰贝阿里港',
      eta: '2025-04-12',
      currentLocation: '印度洋（N12°38\', E68°14\'）',
      riskLevel: 'medium',
      cargo: '电子产品（3×40HQ）',
      weight: '62.4 吨',
      insured: true,
      policyNo: 'INS-ME-2025-0001',
      timeline: [
        { time: '2025-03-18 09:00', location: '上海洋山港', status: 'completed', event: '货物装船完成', detail: 'MSC DUBAI EXPRESS / 舱位 BAY12-ROW08' },
        { time: '2025-03-19 14:30', location: '上海洋山港', status: 'completed', event: '海关放行', detail: '海关监管放行，单证完备' },
        { time: '2025-03-20 06:00', location: '上海洋山港', status: 'completed', event: '船舶离港', detail: '正式起航，预计航行 24 天' },
        { time: '2025-03-25 16:00', location: '马六甲海峡', status: 'completed', event: '过境马六甲', detail: '通行顺利，无延误' },
        { time: '2025-03-28 11:00', location: '斯里兰卡科伦坡', status: 'completed', event: '中转换装', detail: '转至支线船 MSC GULF STAR' },
        { time: '2025-04-02 08:00', location: '印度洋', status: 'in-progress', event: '绕行好望角航段', detail: '因红海安全形势，船公司决策绕行，延期约 5 天' },
        { time: '2025-04-08 00:00', location: '阿拉伯海', status: 'pending', event: '进入阿拉伯海', detail: '预计抵达时间 2025-04-08' },
        { time: '2025-04-12 08:00', location: '迪拜杰贝阿里港', status: 'pending', event: '预计到港', detail: '目标泊位 CT2-B12，需提前预约提柜' },
      ]
    },
    'ME20250002': {
      trackingNo: 'ME20250002',
      carrier: '阿联酋航空货运',
      vessel: 'EK9721 (B777F)',
      voyage: 'EK9721',
      origin: '广州白云国际机场',
      destination: '迪拜货运村',
      eta: '2025-03-20',
      currentLocation: '迪拜货运村（到港待提）',
      riskLevel: 'low',
      cargo: '奢侈品/珠宝（1 AWB）',
      weight: '380 KG',
      insured: true,
      policyNo: 'INS-ME-2025-0012',
      timeline: [
        { time: '2025-03-17 18:00', location: '广州白云机场', status: 'completed', event: '货物交运', detail: '安检过机，温控仓储' },
        { time: '2025-03-17 23:45', location: '广州白云机场', status: 'completed', event: '航班起飞', detail: 'EK9721 准时起飞' },
        { time: '2025-03-18 05:30', location: '迪拜国际机场', status: 'completed', event: '航班落地', detail: '到港，移交货站处理' },
        { time: '2025-03-18 10:00', location: '迪拜货运村', status: 'completed', event: '海关申报完成', detail: '清关通过，可提货' },
        { time: '2025-03-20 00:00', location: '迪拜货运村', status: 'in-progress', event: '等待收货人提货', detail: '货物存放于安全区域，提货期限 7 日' },
      ]
    },
    'ME20250003': {
      trackingNo: 'ME20250003',
      carrier: '中远海运（COSCO）',
      vessel: 'COSCO SAUDI ARABIA',
      voyage: 'CS2503E',
      origin: '宁波舟山港',
      destination: '沙特阿拉伯达曼港',
      eta: '2025-04-18',
      currentLocation: '红海（绕行警告区域）',
      riskLevel: 'high',
      cargo: '建材/钢材（5×20GP）',
      weight: '156.8 吨',
      insured: true,
      policyNo: 'INS-ME-2025-0023',
      timeline: [
        { time: '2025-03-10 10:00', location: '宁波舟山港', status: 'completed', event: '货物装船', detail: '5 个 20\' 标准集装箱，积载完成' },
        { time: '2025-03-11 08:00', location: '宁波舟山港', status: 'completed', event: '船舶离港', detail: '顺利起航' },
        { time: '2025-03-18 14:00', location: '红海北部', status: 'in-progress', event: '风险区域航行中', detail: '⚠️ 高风险：胡塞武装活动区域，船舶已启动紧急应急预案' },
        { time: '2025-03-22 00:00', location: '霍尔木兹海峡', status: 'pending', event: '预计过境霍尔木兹', detail: '需关注伊朗局势' },
        { time: '2025-04-18 06:00', location: '达曼港', status: 'pending', event: '预计到港', detail: '高风险延误概率 35%' },
      ]
    },
    'ME20250004': {
      trackingNo: 'ME20250004',
      carrier: '土耳其航空货运',
      vessel: 'TK6701 (B777F)',
      voyage: 'TK6701',
      origin: '成都天府国际机场',
      destination: '伊斯坦布尔阿塔图尔克机场',
      eta: '2025-03-19',
      currentLocation: '伊斯坦布尔清关中',
      riskLevel: 'low',
      cargo: '汽车零部件（6 AWB）',
      weight: '2,840 KG',
      insured: true,
      policyNo: 'INS-ME-2025-0034',
      timeline: [
        { time: '2025-03-17 14:00', location: '成都天府机场', status: 'completed', event: '货物交运检查', detail: '危品复核通过，正常货物' },
        { time: '2025-03-17 20:00', location: '成都天府机场', status: 'completed', event: '航班起飞', detail: 'TK6701 准时' },
        { time: '2025-03-18 06:00', location: '伊斯坦布尔机场', status: 'completed', event: '到港入库', detail: '货物完好，移送海关监管区' },
        { time: '2025-03-18 16:00', location: '伊斯坦布尔机场', status: 'in-progress', event: '海关查验中', detail: '随机抽查，预计 24 小时内完成' },
        { time: '2025-03-19 16:00', location: '伊斯坦布尔', status: 'pending', event: '预计清关放行', detail: '' },
      ]
    },
    'ME20250005': {
      trackingNo: 'ME20250005',
      carrier: '马士基航运（MAERSK）',
      vessel: 'MAERSK CAIRO',
      voyage: 'AE7-N',
      origin: '天津港',
      destination: '埃及塞得港',
      eta: '2025-04-05',
      currentLocation: '地中海（E29°52\', N31°16\'）',
      riskLevel: 'medium',
      cargo: '纺织品（8×40GP）',
      weight: '198.4 吨',
      insured: false,
      policyNo: null,
      timeline: [
        { time: '2025-03-05 09:00', location: '天津港', status: 'completed', event: '装船完成', detail: '8 箱已装，封铅完好' },
        { time: '2025-03-06 12:00', location: '天津港', status: 'completed', event: '船舶起航', detail: '' },
        { time: '2025-03-20 08:00', location: '苏伊士运河', status: 'completed', event: '过境苏伊士运河', detail: '排队等候约 8 小时，正常通行' },
        { time: '2025-03-21 14:00', location: '地中海', status: 'in-progress', event: '地中海航行中', detail: '距目的港约 600 海里' },
        { time: '2025-04-05 10:00', location: '塞得港', status: 'pending', event: '预计到港', detail: '⚠️ 该票货物未购买运输险，建议尽快投保' },
      ]
    },
    'ME20250006': {
      trackingNo: 'ME20250006',
      carrier: '以色列货运航空（CAL）',
      vessel: 'CAL 5P (B747F)',
      voyage: '5P801',
      origin: '深圳宝安国际机场',
      destination: '特拉维夫本古里安机场',
      eta: '2025-03-22',
      currentLocation: '亚洲航路（IN TRANSIT）',
      riskLevel: 'medium',
      cargo: '医疗器械（2 AWB）',
      weight: '920 KG',
      insured: true,
      policyNo: 'INS-ME-2025-0056',
      timeline: [
        { time: '2025-03-19 22:00', location: '深圳宝安机场', status: 'completed', event: '货物起飞', detail: '医疗器械专项申报通过' },
        { time: '2025-03-20 10:00', location: '迪拜中转', status: 'completed', event: '迪拜中转换装', detail: '转至以航航班' },
        { time: '2025-03-20 18:00', location: '亚洲航路', status: 'in-progress', event: '航班在途', detail: '⚡ 中风险：中东局势影响部分空域' },
        { time: '2025-03-22 06:00', location: '特拉维夫', status: 'pending', event: '预计到港', detail: '目前空运保险附加费率上调' },
      ]
    },
    'ME20250007': {
      trackingNo: 'ME20250007',
      carrier: '伊朗国家航运公司（IRISL）',
      vessel: 'IRAN SHAHED',
      voyage: 'IS2503N',
      origin: '广州南沙港',
      destination: '伊朗班达尔阿巴斯港',
      eta: '2025-04-20',
      currentLocation: '阿拉伯海（N22°10\', E61°32\'）',
      riskLevel: 'high',
      cargo: '工业机械（2×40OT）',
      weight: '87.3 吨',
      insured: true,
      policyNo: 'INS-ME-2025-0067',
      timeline: [
        { time: '2025-03-08 08:00', location: '广州南沙港', status: 'completed', event: '特种设备装船', detail: '超限货物，使用开顶箱' },
        { time: '2025-03-09 16:00', location: '广州南沙港', status: 'completed', event: '离港', detail: '制裁合规审查通过' },
        { time: '2025-03-18 12:00', location: '阿拉伯海', status: 'in-progress', event: '阿拉伯海航行', detail: '⚠️ 高风险：接近伊朗制裁区域，保险附加条款生效' },
        { time: '2025-04-15 00:00', location: '霍尔木兹海峡', status: 'pending', event: '预计过境霍尔木兹', detail: '需要特别申报' },
        { time: '2025-04-20 14:00', location: '班达尔阿巴斯港', status: 'pending', event: '预计到港', detail: '' },
      ]
    },
    'ME20250008': {
      trackingNo: 'ME20250008',
      carrier: '阿提哈德货运',
      vessel: 'EY8431 (B777F)',
      voyage: 'EY8431',
      origin: '武汉天河国际机场',
      destination: '阿布扎比国际机场',
      eta: '2025-03-19',
      currentLocation: '已到港，待收货',
      riskLevel: 'low',
      cargo: '光伏组件（4 AWB）',
      weight: '6,200 KG',
      insured: true,
      policyNo: 'INS-ME-2025-0078',
      timeline: [
        { time: '2025-03-18 16:00', location: '武汉天河机场', status: 'completed', event: '货物交运', detail: '易碎品特殊标识已贴附' },
        { time: '2025-03-18 21:00', location: '武汉天河机场', status: 'completed', event: '航班起飞', detail: 'EY8431 准时起飞' },
        { time: '2025-03-19 05:00', location: '阿布扎比机场', status: 'completed', event: '航班落地', detail: '货物完好到港' },
        { time: '2025-03-19 11:00', location: '阿布扎比货运站', status: 'in-progress', event: '等待清关', detail: '预计 4 小时完成' },
        { time: '2025-03-19 15:00', location: '阿布扎比', status: 'pending', event: '预计可提货', detail: '' },
      ]
    },
    'ME20250009': {
      trackingNo: 'ME20250009',
      carrier: '卡塔尔货运',
      vessel: 'QR8621 (B777F)',
      voyage: 'QR8621',
      origin: '上海浦东国际机场',
      destination: '多哈哈马德国际机场',
      eta: '2025-03-21',
      currentLocation: '上海浦东机场（等待起飞）',
      riskLevel: 'low',
      cargo: '食品（速冻海鲜，5 AWB）',
      weight: '4,500 KG',
      insured: true,
      policyNo: 'INS-ME-2025-0089',
      timeline: [
        { time: '2025-03-20 14:00', location: '上海浦东机场', status: 'completed', event: '温控货物验收', detail: '-18℃ 冷链完整，检验合格' },
        { time: '2025-03-20 18:00', location: '上海浦东机场', status: 'in-progress', event: '等待航班', detail: 'QR8621 预计 21:30 起飞' },
        { time: '2025-03-21 02:00', location: '多哈机场', status: 'pending', event: '预计到港', detail: '冷链交接需全程温控记录' },
        { time: '2025-03-21 06:00', location: '多哈', status: 'pending', event: '清关提货', detail: '进口商已准备提货手续' },
      ]
    },
    'ME20250010': {
      trackingNo: 'ME20250010',
      carrier: '沙特阿拉伯航空货运',
      vessel: 'SV6142 (B777F)',
      voyage: 'SV6142',
      origin: '北京首都国际机场',
      destination: '沙特利雅得阿卜杜勒阿齐兹国王机场',
      eta: '2025-03-20',
      currentLocation: '利雅得（延误查验中）',
      riskLevel: 'medium',
      cargo: '信息技术设备（3 AWB）',
      weight: '1,650 KG',
      insured: true,
      policyNo: 'INS-ME-2025-0099',
      timeline: [
        { time: '2025-03-18 22:00', location: '北京首都机场', status: 'completed', event: '货物起飞', detail: '双重安检通过' },
        { time: '2025-03-19 05:00', location: '利雅得机场', status: 'completed', event: '到港入库', detail: '货物完好' },
        { time: '2025-03-19 10:00', location: '利雅得海关', status: 'in-progress', event: '海关技术安全查验', detail: '⚡ 中风险：IT 设备需通信技术监管局（CITC）认证核查，预计延误 48 小时' },
        { time: '2025-03-21 10:00', location: '利雅得', status: 'pending', event: '预计清关放行', detail: '建议收货方跟进认证文件' },
      ]
    },
  },

  // Insurance policy data
  insurance: {
    'INS-ME-2025-0001': {
      policyNo: 'INS-ME-2025-0001',
      insured: '华南电子科技有限公司',
      insurer: '中国太平洋财产保险',
      cargoType: '电子产品（消费电子/零部件）',
      coverageAmount: 'USD 1,850,000',
      premium: 'USD 5,550',
      rate: '0.30%',
      startDate: '2025-03-18',
      endDate: '2025-05-18',
      status: 'active',
      riskLevel: 'medium',
      trackingNo: 'ME20250001',
      route: '上海 → 迪拜（杰贝阿里港）',
      transport: '海运',
      deductible: 'USD 5,000',
      coverage: ['全损', '部分损失', '共同海损', '碰撞', '火灾', '盗窃', '自然灾害'],
      exclusions: ['战争险（附加投保）', '罢工险（附加投保）', 'SRCC险'],
      claimHistory: [],
      conditions: '适用协会货物条款 A 款，含战争险附加条款（红海绕行）',
    },
    'INS-ME-2025-0012': {
      policyNo: 'INS-ME-2025-0012',
      insured: '上海奢侈品贸易有限公司',
      insurer: '人保财险（PICC）',
      cargoType: '高值商品（珠宝/手表）',
      coverageAmount: 'USD 3,200,000',
      premium: 'USD 16,000',
      rate: '0.50%',
      startDate: '2025-03-17',
      endDate: '2025-04-17',
      status: 'active',
      riskLevel: 'low',
      trackingNo: 'ME20250002',
      route: '广州 → 迪拜（航空）',
      transport: '航空',
      deductible: 'USD 0（全额赔付）',
      coverage: ['全险', '盗窃', '劫机/劫货', '温控失效', '包装破损'],
      exclusions: ['主动放弃', '货值申报不实'],
      claimHistory: [],
      conditions: '高价值货物专项险，强制武装押运，温控全程监控',
    },
    'INS-ME-2025-0023': {
      policyNo: 'INS-ME-2025-0023',
      insured: '天津钢铁建材集团',
      insurer: '平安财险',
      cargoType: '建材/钢铁制品',
      coverageAmount: 'USD 890,000',
      premium: 'USD 4,450',
      rate: '0.50%（含战争险附加费率 0.15%）',
      startDate: '2025-03-10',
      endDate: '2025-05-10',
      status: 'active',
      riskLevel: 'high',
      trackingNo: 'ME20250003',
      route: '宁波 → 沙特达曼港（海运）',
      transport: '海运',
      deductible: 'USD 10,000',
      coverage: ['全损', '部分损失', '共同海损', '战争险', '罢工险', 'SRCC险'],
      exclusions: ['自然腐蚀', '货物固有缺陷'],
      claimHistory: [
        { date: '2024-11-15', type: '部分损失', amount: 'USD 35,000', status: '已赔付', desc: '因台风导致集装箱内钢材受损' }
      ],
      conditions: '⚠️ 高风险：红海航线战争险已激活，保险公司密切追踪船舶位置',
    },
    'INS-ME-2025-0034': {
      policyNo: 'INS-ME-2025-0034',
      insured: '成都汽车零部件出口商',
      insurer: '中国平安',
      cargoType: '汽车零部件',
      coverageAmount: 'USD 420,000',
      premium: 'USD 840',
      rate: '0.20%',
      startDate: '2025-03-17',
      endDate: '2025-04-17',
      status: 'active',
      riskLevel: 'low',
      trackingNo: 'ME20250004',
      route: '成都 → 伊斯坦布尔（航空）',
      transport: '航空',
      deductible: 'USD 2,000',
      coverage: ['全损', '部分损失', '运输延误（超 72 小时补偿）'],
      exclusions: ['战争险', '内部漏洞/软件缺陷'],
      claimHistory: [],
      conditions: '标准航空运输险，适用协会航空货物条款',
    },
    'INS-ME-2025-0056': {
      policyNo: 'INS-ME-2025-0056',
      insured: '深圳医疗器械科技公司',
      insurer: '太平财险',
      cargoType: '医疗器械（II 类）',
      coverageAmount: 'USD 560,000',
      premium: 'USD 1,680',
      rate: '0.30%',
      startDate: '2025-03-19',
      endDate: '2025-04-19',
      status: 'active',
      riskLevel: 'medium',
      trackingNo: 'ME20250006',
      route: '深圳 → 特拉维夫（航空）',
      transport: '航空',
      deductible: 'USD 3,000',
      coverage: ['全损', '破损', '温控失效', '政治风险（有限）'],
      exclusions: ['核辐射', '生物污染', '战争险'],
      claimHistory: [],
      conditions: '⚡ 中风险：中东局势影响空域，已通知被保险人延误风险',
    },
    'INS-ME-2025-0067': {
      policyNo: 'INS-ME-2025-0067',
      insured: '广州工程机械出口有限公司',
      insurer: '中国出口信用保险公司（Sinosure）',
      cargoType: '工业机械（超限货物）',
      coverageAmount: 'USD 2,100,000',
      premium: 'USD 12,600',
      rate: '0.60%（含制裁风险附加费率 0.15%）',
      startDate: '2025-03-08',
      endDate: '2025-05-08',
      status: 'active',
      riskLevel: 'high',
      trackingNo: 'ME20250007',
      route: '广州 → 伊朗班达尔阿巴斯（海运）',
      transport: '海运',
      deductible: 'USD 20,000',
      coverage: ['全损', '部分损失', '战争险', '制裁合规险', '政治风险'],
      exclusions: ['制裁违规行为', '货物用途改变'],
      claimHistory: [
        { date: '2024-06-20', type: '延误损失', amount: 'USD 18,500', status: '已赔付', desc: '因霍尔木兹海峡临时封锁导致延误' }
      ],
      conditions: '⚠️ 高风险：制裁合规条款严格，需定期提交合规报告',
    },
    'INS-ME-2025-0078': {
      policyNo: 'INS-ME-2025-0078',
      insured: '武汉光伏能源设备公司',
      insurer: '中国人寿财险',
      cargoType: '光伏组件（太阳能面板）',
      coverageAmount: 'USD 680,000',
      premium: 'USD 1,360',
      rate: '0.20%',
      startDate: '2025-03-18',
      endDate: '2025-04-18',
      status: 'active',
      riskLevel: 'low',
      trackingNo: 'ME20250008',
      route: '武汉 → 阿布扎比（航空）',
      transport: '航空',
      deductible: 'USD 5,000',
      coverage: ['全损', '破损', '搬运损伤'],
      exclusions: ['过压/欠压损害', '自然老化'],
      claimHistory: [],
      conditions: '清洁能源设备出口专项险，对阿联酋可再生能源项目优先理赔',
    },
    'INS-ME-2025-0089': {
      policyNo: 'INS-ME-2025-0089',
      insured: '上海远洋渔业冷链物流',
      insurer: '太平洋财险',
      cargoType: '冷冻食品（速冻海鲜）',
      coverageAmount: 'USD 95,000',
      premium: 'USD 380',
      rate: '0.40%',
      startDate: '2025-03-20',
      endDate: '2025-04-05',
      status: 'active',
      riskLevel: 'low',
      trackingNo: 'ME20250009',
      route: '上海 → 多哈（航空冷链）',
      transport: '航空',
      deductible: 'USD 1,000',
      coverage: ['全损', '温控失效（超出允差）', '冷链中断'],
      exclusions: ['非强制冷链环节中断', '包装问题导致污染'],
      claimHistory: [],
      conditions: '温控险：全程温度记录仪监控，温差超 ±2℃ 触发理赔',
    },
    'INS-ME-2025-0099': {
      policyNo: 'INS-ME-2025-0099',
      insured: '北京信息技术出口有限公司',
      insurer: '华泰财险',
      cargoType: '信息技术设备（服务器/网络设备）',
      coverageAmount: 'USD 320,000',
      premium: 'USD 960',
      rate: '0.30%',
      startDate: '2025-03-18',
      endDate: '2025-04-18',
      status: 'active',
      riskLevel: 'medium',
      trackingNo: 'ME20250010',
      route: '北京 → 利雅得（航空）',
      transport: '航空',
      deductible: 'USD 2,500',
      coverage: ['全损', '部分损失', '海关扣押险（等待期 30 天）', '延误补偿'],
      exclusions: ['软件/数据损失', '认证不符导致拒绝进口'],
      claimHistory: [],
      conditions: '⚡ 中风险：沙特 CITC 认证延误已触发保单延误条款，理赔申请通道已开放',
    },
  },

  // Risk map data per country
  riskMap: {
    'SA': { name: '沙特阿拉伯', riskLevel: 'medium', inTransit: '12,450 TEU', coverage: '72.4%', events: ['吉达港扩建工程延误', '内陆陆运路线优化', 'CITC 法规更新'], color: '#f59e0b' },
    'AE': { name: '阿联酋', riskLevel: 'low',    inTransit: '28,930 TEU', coverage: '85.1%', events: ['杰贝阿里港数字化升级', '自贸区保险新政', '空运量创历史新高'], color: '#22c55e' },
    'IR': { name: '伊朗',    riskLevel: 'high',   inTransit: '3,210 TEU',  coverage: '38.6%', events: ['制裁令新增限制条款', '霍尔木兹海峡演习', '银行结算受阻'], color: '#ef4444' },
    'IL': { name: '以色列',  riskLevel: 'medium', inTransit: '4,780 TEU',  coverage: '78.3%', events: ['本古里安机场安全强化', '加沙局势影响周边物流', '特拉维夫港限行'], color: '#f59e0b' },
    'YE': { name: '也门',    riskLevel: 'critical',inTransit: '680 TEU',   coverage: '12.7%', events: ['胡塞武装持续袭击红海船只', '亚丁港吞吐量下降 67%', '人道主义货物优先通行'], color: '#dc2626' },
    'TR': { name: '土耳其',  riskLevel: 'low',    inTransit: '19,200 TEU', coverage: '65.9%', events: ['伊斯坦布尔新机场成为地区枢纽', '里拉汇率波动影响保费', '欧亚陆路走廊增量'], color: '#22c55e' },
    'EG': { name: '埃及',    riskLevel: 'medium', inTransit: '9,840 TEU',  coverage: '44.2%', events: ['苏伊士运河新收费标准', '塞得港扩建第二期', '外汇短缺影响清关效率'], color: '#f59e0b' },
    'QA': { name: '卡塔尔',  riskLevel: 'low',    inTransit: '5,100 TEU',  coverage: '70.5%', events: ['多哈港冷链设施升级', '世界杯后续物流基建利用', '与周边国家关系正常化'], color: '#22c55e' },
    'KW': { name: '科威特',  riskLevel: 'low',    inTransit: '3,670 TEU',  coverage: '68.2%', events: ['科威特港口现代化项目', '石油化工物流增长', '清关流程数字化'], color: '#22c55e' },
    'OM': { name: '阿曼',    riskLevel: 'low',    inTransit: '4,520 TEU',  coverage: '62.8%', events: ['萨拉拉港绕行受益增长', 'Duqm 经济区吸引投资', '保险法修订利好外资'], color: '#22c55e' },
    'JO': { name: '约旦',    riskLevel: 'medium', inTransit: '1,980 TEU',  coverage: '55.3%', events: ['亚喀巴港中转量上升', '陆路走廊受地区局势影响', '难民潮带来人道物流需求'], color: '#f59e0b' },
    'IQ': { name: '伊拉克',  riskLevel: 'high',   inTransit: '2,340 TEU',  coverage: '29.4%', events: ['巴士拉港安全局势紧张', '民兵武装影响陆路运输', '重建物资进口大幅增加'], color: '#ef4444' },
  },

  // Key chokepoints
  chokepoints: [
    { name: '苏伊士运河', status: 'operational', risk: 'medium', desc: '通行基本正常，排队 8-12 小时，附近防范上升' },
    { name: '红海（曼德海峡）', status: 'dangerous', risk: 'high', desc: '胡塞武装袭击活跃，多家船公司绕行好望角' },
    { name: '霍尔木兹海峡', status: 'caution', risk: 'medium', desc: '伊朗-美国紧张，海军巡逻加强，有扣押风险' },
    { name: '波斯湾', status: 'normal', risk: 'low', desc: '主要港口运营正常，沙尘暴季节需注意' },
    { name: '阿拉伯海', status: 'caution', risk: 'medium', desc: '索马里海盗活动低频，季风季节即将来临' },
  ]
};

// ── Merge localStorage overrides (written by admin panel) ─────────────────────
(function () {
  try {
    const raw = localStorage.getItem('mideast_admin_data');
    if (!raw) return;
    const saved = JSON.parse(raw);
    if (saved.logistics) DATA.logistics = saved.logistics;
    if (saved.insurance) DATA.insurance = saved.insurance;
    if (saved.riskMap)   DATA.riskMap   = saved.riskMap;
  } catch (e) { /* ignore corrupt data */ }
})();
